# Generated by Django 3.1.7 on 2021-02-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20210228_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.client'),
        ),
    ]
