# Generated by Django 3.1.7 on 2021-03-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20210303_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
