# Generated by Django 3.1.7 on 2021-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=100),
        ),
    ]
