# Generated by Django 3.1.7 on 2021-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20210307_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
