# Generated by Django 3.1.7 on 2021-03-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
